/* auth */
export const LOGIN_OUT = 'LOGIN_OUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const SET_HTTP_HEADERS = 'SET_HTTP_HEADERS';
export const SET_HOST_URL = 'SET_HOST_URL';
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION';
export const UPDATE_FACTORYLIST = 'UPDATE_FACTORYLIST';
export const UPDATE_BANNERLIST = 'UPDATE_BANNERLIST';
export const UPDATE_INDEXNAV = 'UPDATE_INDEXNAV';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_HIDECUSTOM = 'UPDATE_HIDECUSTOM';
export const UPDATE_IS_ALL = 'UPDATE_IS_ALL';
export const SET_LANGUAGE_SHOW = 'SET_LANGUAGE_SHOW';
export const SET_LANGUAGE_LISTS = 'SET_LANGUAGE_LISTS';
export const CHANGE_SHOWLEFT = 'CHANGE_SHOWLEFT';
export const SET_VIP_LIST = 'SET_VIP_LIST';

